project:
  type: website
  output-dir: docs

website:
  title: "Sciencing the data"
  navbar:
    right:
      - text: "about"
        href: about.qmd
      - icon: github
        href: https://github.com/chris-kelly
      - icon: linkedin
        href: https://www.linkedin.com/in/ccrkelly/
format:
  html:
    theme: lux
    css: styles.css



